version: '2'
services:
  ldev-api:
    build: .
    container_name: ldev-api
    hostname: ldev-api
    volumes:
      - "./config/ldev.yml:/config/ldev.yml"
    ports:
      - "8080:80"
    network_mode: bridge
    external_links:
      - postgres:postgres
    environment:
      - ENV=ldev
